# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GateCli < Formula
  desc "Gate CLI - command-line interface for Gate"
  homepage "https://www.gate.com"
  version "0.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gate/gate-cli/releases/download/v0.4.0/gate-cli_0.4.0_darwin_amd64.tar.gz"
      sha256 "1178bf3b41fe4be1597590e26edca1297b9cac7f630d3c81f3e455d2524e2b39"

      define_method(:install) do
        bin.install "gate-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/gate/gate-cli/releases/download/v0.4.0/gate-cli_0.4.0_darwin_arm64.tar.gz"
      sha256 "d72f555aae02a4e8d57c58da0e3259b3247ec0bec8f13e1d3f7abc71da08d544"

      define_method(:install) do
        bin.install "gate-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/gate/gate-cli/releases/download/v0.4.0/gate-cli_0.4.0_linux_amd64.tar.gz"
      sha256 "b41c4007ff85b856f0adfdbf3713469202339ede1b08a76d8924e8579af11a40"
      define_method(:install) do
        bin.install "gate-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gate/gate-cli/releases/download/v0.4.0/gate-cli_0.4.0_linux_arm64.tar.gz"
      sha256 "1522235e92549dbfdfdd009fe583eb01bbd8e521c76075a55eb565f510701956"
      define_method(:install) do
        bin.install "gate-cli"
      end
    end
  end

  test do
    system bin/"gate-cli", "--version"
  end
end
