# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GateCli < Formula
  desc "Gate CLI - command-line interface for Gate"
  homepage "https://www.gate.com"
  version "0.5.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gate/gate-cli/releases/download/v0.5.1/gate-cli_0.5.1_darwin_amd64.tar.gz"
      sha256 "042e29dac71c2fe5bf12e3b3a4f940114abe663341b15e5516e3023c4c875c0f"

      define_method(:install) do
        bin.install "gate-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/gate/gate-cli/releases/download/v0.5.1/gate-cli_0.5.1_darwin_arm64.tar.gz"
      sha256 "9820407b4ab4eebff74476468b2d78624f2d85665a1215c693d903a1cb915b07"

      define_method(:install) do
        bin.install "gate-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/gate/gate-cli/releases/download/v0.5.1/gate-cli_0.5.1_linux_amd64.tar.gz"
      sha256 "b7e8527cf33b5bf08b621789b2ed30c166ca74d7a9cf56acab0afb3b7ee6f549"
      define_method(:install) do
        bin.install "gate-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gate/gate-cli/releases/download/v0.5.1/gate-cli_0.5.1_linux_arm64.tar.gz"
      sha256 "b19da98d87f40428a25ecec111d2bdbcd911d8a70ad6ff55606b46887beb4d58"
      define_method(:install) do
        bin.install "gate-cli"
      end
    end
  end

  test do
    system bin/"gate-cli", "--version"
  end
end
