# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GateCli < Formula
  desc "Gate CLI - command-line interface for Gate"
  homepage "https://www.gate.com"
  version "0.7.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gate/gate-cli/releases/download/v0.7.2/gate-cli_0.7.2_darwin_amd64.tar.gz"
      sha256 "6818dc13e623264bcedbcf9f436f3ff1b23c23cdd62a3e3b4ccc18a90cb4d9b8"

      define_method(:install) do
        bin.install "gate-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/gate/gate-cli/releases/download/v0.7.2/gate-cli_0.7.2_darwin_arm64.tar.gz"
      sha256 "ff4b03409f4b93d89a8febd21f89cdb53e4167461cfa8dce102a04e7e3dca768"

      define_method(:install) do
        bin.install "gate-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/gate/gate-cli/releases/download/v0.7.2/gate-cli_0.7.2_linux_amd64.tar.gz"
      sha256 "4daca63d238358d8b79dcbc28a95e5451ce5af78ec7d6aa08aa31b0fef08bf34"
      define_method(:install) do
        bin.install "gate-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gate/gate-cli/releases/download/v0.7.2/gate-cli_0.7.2_linux_arm64.tar.gz"
      sha256 "5545ed45663badbd37692e6ff481d59c2d2dd8ef16afe8fa23d92814245a5ae9"
      define_method(:install) do
        bin.install "gate-cli"
      end
    end
  end

  test do
    system bin/"gate-cli", "--version"
  end
end
