# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GateCli < Formula
  desc "Gate CLI - command-line interface for Gate"
  homepage "https://www.gate.com"
  version "0.5.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gate/gate-cli/releases/download/v0.5.2/gate-cli_0.5.2_darwin_amd64.tar.gz"
      sha256 "635816261760bf540c09972c00509ee693d22c139f6028f372e4228052511e7d"

      define_method(:install) do
        bin.install "gate-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/gate/gate-cli/releases/download/v0.5.2/gate-cli_0.5.2_darwin_arm64.tar.gz"
      sha256 "e781ed8cb00c5d7f737d2c52f62210581a38e4417108c55a9ca700b9aff3427b"

      define_method(:install) do
        bin.install "gate-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/gate/gate-cli/releases/download/v0.5.2/gate-cli_0.5.2_linux_amd64.tar.gz"
      sha256 "61c28a066dba4d3e362c2fc208165a05d0af68818928a4bce879f2d27e6c23d0"
      define_method(:install) do
        bin.install "gate-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gate/gate-cli/releases/download/v0.5.2/gate-cli_0.5.2_linux_arm64.tar.gz"
      sha256 "91e9e6c1d818382e181ff1467505636356bdd85c9de5fc07988f19648838ddb3"
      define_method(:install) do
        bin.install "gate-cli"
      end
    end
  end

  test do
    system bin/"gate-cli", "--version"
  end
end
